import "./globals.css";
import { Inter } from "next/font/google";

import { WagmiProvider } from "@/Components/WagmiProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Eigen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="cupcake" lang="en">
      <WagmiProvider>
        <body className={inter.className}>{children}</body>
      </WagmiProvider>
    </html>
  );
}
