import "./globals.css";
import { DM_Sans } from "next/font/google";

import { WagmiProvider } from "@/Components/WagmiProvider";

const inter = DM_Sans({ weight: ["500", "400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Eigen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <WagmiProvider>
        <body className={inter.className}>{children}</body>
      </WagmiProvider>
    </html>
  );
}
